version: '3'

services:
  target-mysql:
    image: mysql:8.0.2
    environment:
      MYSQL_DATABASE: jobs_board
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
    - jobs_board_network

  web:
    build: .
    command: >
      bash -c " python3.6 manage.py makemigrations jb_dashboard
      && python3.6 manage.py migrate --fake jb_dashboard
      && python3.6 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - target-mysql
    networks:
      - jobs_board_network

networks:
  jobs_board_network:
